package org.nzbhydra.config.downloading;

import org.assertj.core.api.AbstractComparableAssert;

/**
 * Abstract base class for {@link FileDownloadAccessType} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractFileDownloadAccessTypeAssert<S extends AbstractFileDownloadAccessTypeAssert<S, A>, A extends FileDownloadAccessType> extends AbstractComparableAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractFileDownloadAccessTypeAssert}</code> to make assertions on actual FileDownloadAccessType.
     *
     * @param actual the FileDownloadAccessType we want to make assertions on.
     */
    protected AbstractFileDownloadAccessTypeAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
