package org.nzbhydra.config.downloading;

/**
 * {@link DownloadingConfig} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractDownloadingConfigAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class DownloadingConfigAssert extends AbstractDownloadingConfigAssert<DownloadingConfigAssert, DownloadingConfig> {

    /**
     * Creates a new <code>{@link DownloadingConfigAssert}</code> to make assertions on actual DownloadingConfig.
     *
     * @param actual the DownloadingConfig we want to make assertions on.
     */
    public DownloadingConfigAssert(DownloadingConfig actual) {
        super(actual, DownloadingConfigAssert.class);
    }

    /**
     * An entry point for DownloadingConfigAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myDownloadingConfig)</code> and get specific assertion with code completion.
     *
     * @param actual the DownloadingConfig we want to make assertions on.
     * @return a new <code>{@link DownloadingConfigAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static DownloadingConfigAssert assertThat(DownloadingConfig actual) {
        return new DownloadingConfigAssert(actual);
    }
}
