package org.nzbhydra.mapping.newznab.json.caps;

/**
 * {@link CapsJsonLimitsAttributes} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractCapsJsonLimitsAttributesAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class CapsJsonLimitsAttributesAssert extends AbstractCapsJsonLimitsAttributesAssert<CapsJsonLimitsAttributesAssert, CapsJsonLimitsAttributes> {

    /**
     * Creates a new <code>{@link CapsJsonLimitsAttributesAssert}</code> to make assertions on actual CapsJsonLimitsAttributes.
     *
     * @param actual the CapsJsonLimitsAttributes we want to make assertions on.
     */
    public CapsJsonLimitsAttributesAssert(CapsJsonLimitsAttributes actual) {
        super(actual, CapsJsonLimitsAttributesAssert.class);
    }

    /**
     * An entry point for CapsJsonLimitsAttributesAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myCapsJsonLimitsAttributes)</code> and get specific assertion with code completion.
     *
     * @param actual the CapsJsonLimitsAttributes we want to make assertions on.
     * @return a new <code>{@link CapsJsonLimitsAttributesAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static CapsJsonLimitsAttributesAssert assertThat(CapsJsonLimitsAttributes actual) {
        return new CapsJsonLimitsAttributesAssert(actual);
    }
}
