package org.nzbhydra.mapping.newznab.json.caps;

/**
 * {@link CapsJsonRegistration} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractCapsJsonRegistrationAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class CapsJsonRegistrationAssert extends AbstractCapsJsonRegistrationAssert<CapsJsonRegistrationAssert, CapsJsonRegistration> {

    /**
     * Creates a new <code>{@link CapsJsonRegistrationAssert}</code> to make assertions on actual CapsJsonRegistration.
     *
     * @param actual the CapsJsonRegistration we want to make assertions on.
     */
    public CapsJsonRegistrationAssert(CapsJsonRegistration actual) {
        super(actual, CapsJsonRegistrationAssert.class);
    }

    /**
     * An entry point for CapsJsonRegistrationAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myCapsJsonRegistration)</code> and get specific assertion with code completion.
     *
     * @param actual the CapsJsonRegistration we want to make assertions on.
     * @return a new <code>{@link CapsJsonRegistrationAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static CapsJsonRegistrationAssert assertThat(CapsJsonRegistration actual) {
        return new CapsJsonRegistrationAssert(actual);
    }
}
