package org.nzbhydra.mapping.newznab.json.caps;

/**
 * {@link CapsJsonSearching} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractCapsJsonSearchingAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class CapsJsonSearchingAssert extends AbstractCapsJsonSearchingAssert<CapsJsonSearchingAssert, CapsJsonSearching> {

    /**
     * Creates a new <code>{@link CapsJsonSearchingAssert}</code> to make assertions on actual CapsJsonSearching.
     *
     * @param actual the CapsJsonSearching we want to make assertions on.
     */
    public CapsJsonSearchingAssert(CapsJsonSearching actual) {
        super(actual, CapsJsonSearchingAssert.class);
    }

    /**
     * An entry point for CapsJsonSearchingAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myCapsJsonSearching)</code> and get specific assertion with code completion.
     *
     * @param actual the CapsJsonSearching we want to make assertions on.
     * @return a new <code>{@link CapsJsonSearchingAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static CapsJsonSearchingAssert assertThat(CapsJsonSearching actual) {
        return new CapsJsonSearchingAssert(actual);
    }
}
