package org.nzbhydra.mapping.newznab.json.caps;

/**
 * {@link CapsJsonSearchIdAttributesHolder} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractCapsJsonSearchIdAttributesHolderAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class CapsJsonSearchIdAttributesHolderAssert extends AbstractCapsJsonSearchIdAttributesHolderAssert<CapsJsonSearchIdAttributesHolderAssert, CapsJsonSearchIdAttributesHolder> {

    /**
     * Creates a new <code>{@link CapsJsonSearchIdAttributesHolderAssert}</code> to make assertions on actual CapsJsonSearchIdAttributesHolder.
     *
     * @param actual the CapsJsonSearchIdAttributesHolder we want to make assertions on.
     */
    public CapsJsonSearchIdAttributesHolderAssert(CapsJsonSearchIdAttributesHolder actual) {
        super(actual, CapsJsonSearchIdAttributesHolderAssert.class);
    }

    /**
     * An entry point for CapsJsonSearchIdAttributesHolderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myCapsJsonSearchIdAttributesHolder)</code> and get specific assertion with code completion.
     *
     * @param actual the CapsJsonSearchIdAttributesHolder we want to make assertions on.
     * @return a new <code>{@link CapsJsonSearchIdAttributesHolderAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static CapsJsonSearchIdAttributesHolderAssert assertThat(CapsJsonSearchIdAttributesHolder actual) {
        return new CapsJsonSearchIdAttributesHolderAssert(actual);
    }
}
