---
version: "2.1"
services:
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    environment:
      - PUID=1026
      - PGID=101
      - TZ=America/Chicago
    volumes:
      - /docker/nzbhydra:/config
      - /Downloads/NZBGet/nzb:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
