package org.nzbhydra.mapping.newznab;

import org.assertj.core.api.AbstractComparableAssert;

/**
 * Abstract base class for {@link OutputType} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractOutputTypeAssert<S extends AbstractOutputTypeAssert<S, A>, A extends OutputType> extends AbstractComparableAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractOutputTypeAssert}</code> to make assertions on actual OutputType.
     *
     * @param actual the OutputType we want to make assertions on.
     */
    protected AbstractOutputTypeAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
