package org.nzbhydra.config.searching;

import org.assertj.core.api.AbstractComparableAssert;

/**
 * Abstract base class for {@link SearchType} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractSearchTypeAssert<S extends AbstractSearchTypeAssert<S, A>, A extends SearchType> extends AbstractComparableAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractSearchTypeAssert}</code> to make assertions on actual SearchType.
     *
     * @param actual the SearchType we want to make assertions on.
     */
    protected AbstractSearchTypeAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
