package org.nzbhydra.config.category;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link NewznabCategoriesDeserializer} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractNewznabCategoriesDeserializerAssert<S extends AbstractNewznabCategoriesDeserializerAssert<S, A>, A extends NewznabCategoriesDeserializer> extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractNewznabCategoriesDeserializerAssert}</code> to make assertions on actual NewznabCategoriesDeserializer.
     *
     * @param actual the NewznabCategoriesDeserializer we want to make assertions on.
     */
    protected AbstractNewznabCategoriesDeserializerAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
