package org.nzbhydra.config.category;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link NewznabCategoriesSerializer} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractNewznabCategoriesSerializerAssert<S extends AbstractNewznabCategoriesSerializerAssert<S, A>, A extends NewznabCategoriesSerializer> extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractNewznabCategoriesSerializerAssert}</code> to make assertions on actual NewznabCategoriesSerializer.
     *
     * @param actual the NewznabCategoriesSerializer we want to make assertions on.
     */
    protected AbstractNewznabCategoriesSerializerAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
