package org.nzbhydra.config.category;

/**
 * {@link CategoriesConfig} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractCategoriesConfigAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class CategoriesConfigAssert extends AbstractCategoriesConfigAssert<CategoriesConfigAssert, CategoriesConfig> {

    /**
     * Creates a new <code>{@link CategoriesConfigAssert}</code> to make assertions on actual CategoriesConfig.
     *
     * @param actual the CategoriesConfig we want to make assertions on.
     */
    public CategoriesConfigAssert(CategoriesConfig actual) {
        super(actual, CategoriesConfigAssert.class);
    }

    /**
     * An entry point for CategoriesConfigAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myCategoriesConfig)</code> and get specific assertion with code completion.
     *
     * @param actual the CategoriesConfig we want to make assertions on.
     * @return a new <code>{@link CategoriesConfigAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static CategoriesConfigAssert assertThat(CategoriesConfig actual) {
        return new CategoriesConfigAssert(actual);
    }
}
