package org.nzbhydra.searching;

/**
 * {@link IndexerSearchEntityTO} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractIndexerSearchEntityTOAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class IndexerSearchEntityTOAssert extends AbstractIndexerSearchEntityTOAssert<IndexerSearchEntityTOAssert, IndexerSearchEntityTO> {

    /**
     * Creates a new <code>{@link IndexerSearchEntityTOAssert}</code> to make assertions on actual IndexerSearchEntityTO.
     *
     * @param actual the IndexerSearchEntityTO we want to make assertions on.
     */
    public IndexerSearchEntityTOAssert(IndexerSearchEntityTO actual) {
        super(actual, IndexerSearchEntityTOAssert.class);
    }

    /**
     * An entry point for IndexerSearchEntityTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myIndexerSearchEntityTO)</code> and get specific assertion with code completion.
     *
     * @param actual the IndexerSearchEntityTO we want to make assertions on.
     * @return a new <code>{@link IndexerSearchEntityTOAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static IndexerSearchEntityTOAssert assertThat(IndexerSearchEntityTO actual) {
        return new IndexerSearchEntityTOAssert(actual);
    }
}
