package org.nzbhydra.config.indexer;

import org.assertj.core.api.AbstractComparableAssert;

/**
 * Abstract base class for {@link BackendType} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractBackendTypeAssert<S extends AbstractBackendTypeAssert<S, A>, A extends BackendType> extends AbstractComparableAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractBackendTypeAssert}</code> to make assertions on actual BackendType.
     *
     * @param actual the BackendType we want to make assertions on.
     */
    protected AbstractBackendTypeAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
