package org.nzbhydra.config.indexer;

/**
 * {@link SearchModuleType} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractSearchModuleTypeAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class SearchModuleTypeAssert extends AbstractSearchModuleTypeAssert<SearchModuleTypeAssert, SearchModuleType> {

    /**
     * Creates a new <code>{@link SearchModuleTypeAssert}</code> to make assertions on actual SearchModuleType.
     *
     * @param actual the SearchModuleType we want to make assertions on.
     */
    public SearchModuleTypeAssert(SearchModuleType actual) {
        super(actual, SearchModuleTypeAssert.class);
    }

    /**
     * An entry point for SearchModuleTypeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(mySearchModuleType)</code> and get specific assertion with code completion.
     *
     * @param actual the SearchModuleType we want to make assertions on.
     * @return a new <code>{@link SearchModuleTypeAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static SearchModuleTypeAssert assertThat(SearchModuleType actual) {
        return new SearchModuleTypeAssert(actual);
    }
}
