package org.nzbhydra.indexers;

/**
 * {@link IndexerEntityTO} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractIndexerEntityTOAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class IndexerEntityTOAssert extends AbstractIndexerEntityTOAssert<IndexerEntityTOAssert, IndexerEntityTO> {

    /**
     * Creates a new <code>{@link IndexerEntityTOAssert}</code> to make assertions on actual IndexerEntityTO.
     *
     * @param actual the IndexerEntityTO we want to make assertions on.
     */
    public IndexerEntityTOAssert(IndexerEntityTO actual) {
        super(actual, IndexerEntityTOAssert.class);
    }

    /**
     * An entry point for IndexerEntityTOAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myIndexerEntityTO)</code> and get specific assertion with code completion.
     *
     * @param actual the IndexerEntityTO we want to make assertions on.
     * @return a new <code>{@link IndexerEntityTOAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static IndexerEntityTOAssert assertThat(IndexerEntityTO actual) {
        return new IndexerEntityTOAssert(actual);
    }
}
