package org.nzbhydra.downloading.downloaders;

/**
 * {@link DownloaderStatus} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractDownloaderStatusAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class DownloaderStatusAssert extends AbstractDownloaderStatusAssert<DownloaderStatusAssert, DownloaderStatus> {

    /**
     * Creates a new <code>{@link DownloaderStatusAssert}</code> to make assertions on actual DownloaderStatus.
     *
     * @param actual the DownloaderStatus we want to make assertions on.
     */
    public DownloaderStatusAssert(DownloaderStatus actual) {
        super(actual, DownloaderStatusAssert.class);
    }

    /**
     * An entry point for DownloaderStatusAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myDownloaderStatus)</code> and get specific assertion with code completion.
     *
     * @param actual the DownloaderStatus we want to make assertions on.
     * @return a new <code>{@link DownloaderStatusAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static DownloaderStatusAssert assertThat(DownloaderStatus actual) {
        return new DownloaderStatusAssert(actual);
    }
}
