package org.nzbhydra.downloading;

/**
 * {@link FileDownloadStatus} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractFileDownloadStatusAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class FileDownloadStatusAssert extends AbstractFileDownloadStatusAssert<FileDownloadStatusAssert, FileDownloadStatus> {

    /**
     * Creates a new <code>{@link FileDownloadStatusAssert}</code> to make assertions on actual FileDownloadStatus.
     *
     * @param actual the FileDownloadStatus we want to make assertions on.
     */
    public FileDownloadStatusAssert(FileDownloadStatus actual) {
        super(actual, FileDownloadStatusAssert.class);
    }

    /**
     * An entry point for FileDownloadStatusAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myFileDownloadStatus)</code> and get specific assertion with code completion.
     *
     * @param actual the FileDownloadStatus we want to make assertions on.
     * @return a new <code>{@link FileDownloadStatusAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static FileDownloadStatusAssert assertThat(FileDownloadStatus actual) {
        return new FileDownloadStatusAssert(actual);
    }
}
