#!/bin/sh
#
# PROVIDE: nzbhydra2
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# nzbhydra2_enable (bool):	Set to NO by default.
#			Set it to YES to enable it.
# nzbhydra2_user:	The user account nzbhydra daemon runs as what
#			you want it to be. It uses '_sabnzbd' user by
#			default. Do not sets it as empty or it will run
#			as root.
# nzbhydra2_group:	The group account nzbhydra daemon runs as what
#			you want it to be. It uses 'nzbhydra2' group by
#			default. Do not sets it as empty or it will run
#			as wheel.
# nzbhydra2_dir:	Directory where nzbhydra lives.
#			Default: /usr/local/nzbhydra2
# nzbhydra2_datafolder:	Data directory for nzbhydra (DB, Logs, config)
#			Default is same as nzbhydra2_dir/data

. /etc/rc.subr

name="nzbhydra2"
rcvar=${name}_enable

load_rc_config ${name}

: ${nzbhydra2_enable:="NO"}
: ${nzbhydra2_user:="nzbhydra2"}
: ${nzbhydra2_group:="nzbhydra2"}
: ${nzbhydra2_dir:="/usr/local/nzbhydra2"}
: ${nzbhydra2_datafolder:="${nzbhydra2_dir}/data"}

pidfile="/var/run/nzbhydra2/nzbhydra2.pid"
command="/usr/local/bin/python3"
command_args="${nzbhydra2_dir}/nzbhydra2wrapperPy3.py --datafolder ${nzbhydra2_datafolder} --pidfile ${pidfile} --daemon --nobrowser"

start_precmd="prestart"
prestart() {
	if [ -f ${pidfile} ]; then
		rm -f ${pidfile}
		echo "Removing stale pidfile."
	elif [ ! -d ${pidfile%/*} ]; then
		install -d -o ${nzbhydra2_user} -g ${nzbhydra2_group} ${pidfile%/*}
	fi

	if [ ! -d ${nzbhydra2_datadir} ]; then
		install -d -o ${nzbhydra2_user} -g ${nzbhydra2_group} ${nzbhydra2_datadir}
	fi
}

run_rc_command "$1"
