ALTER TABLE INDEXERAPIACCESS_SHORT
  ADD COLUMN API_ACCESS_TYPE VARCHAR(255);

ALTER TABLE INDEXERAPIACCESS_SHORT
  DROP CONSTRAINT FKFLRMBYQ8CLDV48KDUNDZHD;

DROP INDEX INDEXERAPIACCESS_SHORT_INDEXER_ID_TIME_INDEX;

CREATE INDEX INDEXERAPIACCESS_SHORT_INDEXER_ID_TYPE_TIME_INDEX
  ON INDEXERAPIACCESS_SHORT (INDEXER_ID, API_ACCESS_TYPE, TIME DESC);

ALTER TABLE INDEXERAPIACCESS_SHORT
  ADD CONSTRAINT FKFLRMBYQ8CLDV48KDUNDZHD
FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID) ON DELETE CASCADE;