DROP TABLE INDEXERAPIACCESS_SHORT;

CREATE TABLE INDEXERAPIACCESS_SHORT
(
  ID              INTEGER PRIMARY KEY NOT NULL,
  INDEXER_ID      INTEGER,
  TIME            TIMESTAMP,
  SUCCESSFUL      BOOLEAN,
  API_ACCESS_TYPE VARCHAR2(255),
  CONSTRAINT FKFLRMBYQ8CLDV48KDUNDZHD FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID)
);


CREATE INDEX INDEXERAPIACCESS_SHORT_ACCESSTYPE_INDEXER_ID_TIME_INDEX
  ON INDEXERAPIACCESS_SHORT (INDEXER_ID, API_ACCESS_TYPE, TIME DESC);


insert into INDEXERAPIACCESS_SHORT (ID, INDEXER_ID, TIME, SUCCESSFUL, API_ACCESS_TYPE)
SELECT HIBERNATE_SEQUENCE.Nextval, x.INDEXER_ID, x.TIME, true, 'SEARCH'
FROM (select A.TIME, A.INDEXER_ID from INDEXERAPIACCESS a where a.TIME > DATEADD('DAY', -2, CURRENT_TIMESTAMP())) x;


insert into INDEXERAPIACCESS_SHORT (ID, INDEXER_ID, TIME, SUCCESSFUL, API_ACCESS_TYPE)
SELECT HIBERNATE_SEQUENCE.Nextval, x.INDEXER_ID, x.TIME, true, 'NZB'
FROM (select D.TIME, R.INDEXER_ID
      from INDEXERNZBDOWNLOAD D
               left join SEARCHRESULT R on D.ID = R.ID
      where d.TIME > DATEADD('DAY', -2, CURRENT_TIMESTAMP())) x;