--For some mysterious reason this needs to be done because otherwise after the migration the next connection to the database will fail with the error that this particular constraint already exists---
ALTER TABLE SEARCHRESULT
  DROP CONSTRAINT FKR5G21PDW3HHS1SEFVJY30TGMI;
ALTER TABLE SEARCHRESULT
  ADD CONSTRAINT FKR5G21PDW3HHS1SEFVJY30TGMI2
FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID) ON DELETE CASCADE;

ALTER TABLE INDEXER
  ADD LAST_ERROR VARCHAR2(4000);
ALTER TABLE INDEXER
  ADD DISABLED_UNTIL TIMESTAMP;
ALTER TABLE INDEXER
  ADD DISABLED_LEVEL INTEGER DEFAULT 1;
ALTER TABLE INDEXER
  ADD STATE VARCHAR2(255) DEFAULT 'ENABLED';