ALTER TABLE SEARCH ADD IP VARCHAR(255);
ALTER TABLE INDEXERNZBDOWNLOAD ADD IP VARCHAR(255);

ALTER TABLE SEARCH ALTER COLUMN USERNAME_OR_IP RENAME TO USERNAME;
ALTER TABLE INDEXERNZBDOWNLOAD ALTER COLUMN USERNAME_OR_IP RENAME TO USERNAME;