CREATE TABLE IF NOT EXISTS INDEXERUNIQUENESSSCORE
(
    ID         INTEGER PRIMARY KEY NOT NULL,
    INDEXER_ID INTEGER             NOT NULL,
    INVOLVED   INTEGER             NOT NULL,
    HAVE       INTEGER             NOT NULL,
    HASRESULT  BOOLEAN             NOT NULL,
    CONSTRAINT MFKFLRMBYQ8CLDV48SWRYIY0YKD2 FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID)
);