CREATE TABLE INDEXERLIMIT
(
    ID              INTEGER PRIMARY KEY NOT NULL,
    INDEXER_ID      INTEGER,
    API_HITS        INTEGER,
    API_HIT_LIMIT   INTEGER,
    DOWNLOADS       INTEGER,
    DOWNLOAD_LIMIT  INTEGER,
    OLDEST_API_HIT  TIMESTAMP,
    OLDEST_DOWNLOAD TIMESTAMP,
    CONSTRAINT DABCDLRMBYQ8CLDV48SWRYIY0YKD2 FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID)
);
