CREATE INDEX INDEXERAPIACCESS_TIME_INDEX ON INDEXERAPIACCESS (TIME DESC);
CREATE INDEX INDEXERNZBDOWNLOAD_TIME_INDEX ON INDEXERNZBDOWNLOAD (TIME DESC);
CREATE INDEX INDEXERNZBDOWNLOAD_SEARCHRESULTID_INDEX ON INDEXERNZBDOWNLOAD (SEARCH_RESULT_ID);
CREATE INDEX SEARCH_TIME_INDEX ON SEARCH (TIME DESC);