ALTER TABLE INDEXERAPIACCESS DROP CONSTRAINT FKFLRMBYQ8CLDV48SWRYIY0YJD2;
ALTER TABLE INDEXERAPIACCESS
  ADD CONSTRAINT FKFLRMBYQ8CLDV48SWRYIY0YJD2
FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID) ON DELETE CASCADE;

ALTER TABLE INDEXERAPIACCESS_SHORT DROP CONSTRAINT FKFLRMBYQ8CLDV48KDUNDZHD;
ALTER TABLE INDEXERAPIACCESS_SHORT
  ADD CONSTRAINT FKFLRMBYQ8CLDV48KDUNDZHD
FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID) ON DELETE CASCADE;

ALTER TABLE INDEXERSEARCH DROP CONSTRAINT FKOBOGIXH7OUOCYK1M0417GYQKR;
ALTER TABLE INDEXERSEARCH
  ADD CONSTRAINT FKOBOGIXH7OUOCYK1M0417GYQKR
FOREIGN KEY (INDEXER_ENTITY_ID) REFERENCES INDEXER (ID) ON DELETE CASCADE;

ALTER TABLE INDEXERSEARCH DROP CONSTRAINT FK48A7TLYKV21V8CEGF6SUCDYGX;
ALTER TABLE INDEXERSEARCH
  ADD CONSTRAINT FK48A7TLYKV21V8CEGF6SUCDYGX
FOREIGN KEY (SEARCH_ENTITY_ID) REFERENCES SEARCH (ID) ON DELETE CASCADE;

ALTER TABLE SEARCHRESULT DROP CONSTRAINT FKR5G21PDW3HHS1SEFVJY30TGMI;
ALTER TABLE SEARCHRESULT
  ADD CONSTRAINT FKR5G21PDW3HHS1SEFVJY30TGMI
FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID) ON DELETE CASCADE;

ALTER TABLE INDEXERNZBDOWNLOAD
  ADD CONSTRAINT FKR5G21PDW3HHS1SEFKHD3HBDGL
FOREIGN KEY (SEARCH_RESULT_ID) REFERENCES SEARCHRESULT (ID) ON DELETE CASCADE;
