-- SQLite-compatible sequences migration
-- This migration creates sequence tables for SQLite since it doesn't support sequences
-- These tables are used by Hibernate for ID generation

CREATE TABLE IF NOT EXISTS IDENTIFIER_KEY_VALUE_PAIR_SEQ (
    next_val INTEGER
);
INSERT INTO IDENTIFIER_KEY_VALUE_PAIR_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS INDEXERAPIACCESS_SEQ (
    next_val INTEGER
);
INSERT INTO INDEXERAPIACCESS_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS INDEXERAPIACCESS_SHORT_SEQ (
    next_val INTEGER
);
INSERT INTO INDEXERAPIACCESS_SHORT_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS INDEXERLIMIT_SEQ (
    next_val INTEGER
);
INSERT INTO INDEXERLIMIT_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS INDEXERNZBDOWNLOAD_SEQ (
    next_val INTEGER
);
INSERT INTO INDEXERNZBDOWNLOAD_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS INDEXERSEARCH_SEQ (
    next_val INTEGER
);
INSERT INTO INDEXERSEARCH_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS INDEXERUNIQUENESSSCORE_SEQ (
    next_val INTEGER
);
INSERT INTO INDEXERUNIQUENESSSCORE_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS INDEXER_SEQ (
    next_val INTEGER
);
INSERT INTO INDEXER_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS MOVIEINFO_SEQ (
    next_val INTEGER
);
INSERT INTO MOVIEINFO_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS NOTIFICATION_SEQ (
    next_val INTEGER
);
INSERT INTO NOTIFICATION_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS SEARCH_SEQ (
    next_val INTEGER
);
INSERT INTO SEARCH_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS SHOWNNEWS_SEQ (
    next_val INTEGER
);
INSERT INTO SHOWNNEWS_SEQ (next_val) VALUES (30000000000);

CREATE TABLE IF NOT EXISTS TVINFO_SEQ (
    next_val INTEGER
);
INSERT INTO TVINFO_SEQ (next_val) VALUES (30000000000); 