-- Keep legacy score rows intact. New observations carry their own timestamp and version.
ALTER TABLE INDEXERUNIQUENESSSCORE ADD COLUMN OBSERVATION_ID CHARACTER VARYING(255);
ALTER TABLE INDEXERUNIQUENESSSCORE ADD COLUMN RECORDED_AT TIMESTAMP;
ALTER TABLE INDEXERUNIQUENESSSCORE ADD COLUMN DATA_VERSION INTEGER;

CREATE TABLE INDEXERSEARCHRESULTOCCURRENCE
(
    ID                INTEGER NOT NULL PRIMARY KEY,
    INDEXER_SEARCH_ID INTEGER NOT NULL,
    SEARCH_RESULT_ID  BIGINT NOT NULL,
    CONSTRAINT ISRO_INDEXER_SEARCH_FK FOREIGN KEY (INDEXER_SEARCH_ID) REFERENCES INDEXERSEARCH (ID) ON DELETE CASCADE,
    CONSTRAINT ISRO_SEARCH_RESULT_FK FOREIGN KEY (SEARCH_RESULT_ID) REFERENCES SEARCHRESULT (ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ISRO_INDEXERSEARCH_RESULT_INDEX ON INDEXERSEARCHRESULTOCCURRENCE (INDEXER_SEARCH_ID, SEARCH_RESULT_ID);
CREATE INDEX ISRO_SEARCH_RESULT_INDEX ON INDEXERSEARCHRESULTOCCURRENCE (SEARCH_RESULT_ID);
CREATE UNIQUE INDEX IUS_OBSERVATION_INDEXER_INDEX ON INDEXERUNIQUENESSSCORE (OBSERVATION_ID, INDEXER_ID);

CREATE SEQUENCE INDEXERSEARCHRESULTOCCURRENCE_SEQ
    INCREMENT BY 1
    START WITH 1;
