ALTER TABLE SEARCH ADD COLUMN MIN_AGE INTEGER;
ALTER TABLE SEARCH ADD COLUMN MAX_AGE INTEGER;
ALTER TABLE SEARCH ADD COLUMN MIN_SIZE INTEGER;
ALTER TABLE SEARCH ADD COLUMN MAX_SIZE INTEGER;

CREATE TABLE SEARCH_SELECTED_INDEXERS
(
    SEARCH_ENTITY_ID INTEGER NOT NULL,
    SELECTED_INDEXERS CHARACTER VARYING(255),
    CONSTRAINT FK_SEARCH_SELECTED_INDEXERS_SEARCH
        FOREIGN KEY (SEARCH_ENTITY_ID) REFERENCES SEARCH
            ON DELETE CASCADE
);
