#! /bin/sh
### BEGIN INIT INFO
# Provides:          NZBHydra
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $NetworkManager
# Should-Stop:       $NetworkManager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of NZBHydra
# Description:       starts instance of NZBHydra using start-stop-daemon
### END INIT INFO

############### EDIT ME ##################
# path to nzbhydra dir
APP_PATH=/opt/nzbhydra

# user
RUN_AS=CHANGEME

# path to nzbhydra bin
DAEMON=/opt/nzbhydra/nzbhydra2

# options for nzbhydra
DAEMON_OPTS="--nobrowser"

# Path to store PID file
PID_PATH=/var/run/nzbhydra
############### END EDIT ME ##################
mkdir -p ${PID_PATH}
PID_FILE=${PID_PATH}/nzbhydra.pid
DESC=`basename ${DAEMON}`
NZBHYDRA_PID=`ps auxf | grep $DAEMON | grep -v grep | awk 'NR==1{print $2}'`

test -x $DAEMON || { echo "$DAEMON must be executable."; exit 1; }

set -e

echo $NZBHYDRA_PID > $PID_FILE

case "$1" in
start)
    if [ -z "${NZBHYDRA_PID}" ]; then
        echo "Starting $DESC"
        rm ${PID_FILE} || return 1
        install -d --mode=0755 -o $RUN_AS $PID_PATH || return 1
        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE --exec $DAEMON -- $DAEMON_OPTS
    else
        echo "${DESC} already running."
    fi
    ;;
stop)
    echo "Stopping $DESC"
    echo $NZBHYDRA_PID > $PID_FILE
    start-stop-daemon --stop --pidfile $PID_FILE --retry 15
    ;;

restart|force-reload)
    echo "Restarting $DESC"
    start-stop-daemon --stop --pidfile $PID_FILE --retry 15
    start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE --exec $DAEMON -- $DAEMON_OPTS
    ;;
*)
     echo "Usage: `basename $0` {start|stop|restart|force-reload}" >&2
     exit 1
    ;;

esac

exit 0
