

package org.nzbhydra.config.notification;

public enum NotificationEventType {

    VIP_RENEWAL_REQUIRED,
    INDEXER_DISABLED,
    INDEXER_REENABLED,
    UPDATE_INSTALLED,
    AUTH_FAILURE,
    RESULT_DOWNLOAD,
    RESULT_DOWNLOAD_COMPLETION,
    EXTERNAL_TOOL_CONFIGURATION

}
