package org.nzbhydra.mapping.newznab.xml;

/**
 * {@link NewznabXmlItem} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractNewznabXmlItemAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class NewznabXmlItemAssert extends AbstractNewznabXmlItemAssert<NewznabXmlItemAssert, NewznabXmlItem> {

    /**
     * Creates a new <code>{@link NewznabXmlItemAssert}</code> to make assertions on actual NewznabXmlItem.
     *
     * @param actual the NewznabXmlItem we want to make assertions on.
     */
    public NewznabXmlItemAssert(NewznabXmlItem actual) {
        super(actual, NewznabXmlItemAssert.class);
    }

    /**
     * An entry point for NewznabXmlItemAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myNewznabXmlItem)</code> and get specific assertion with code completion.
     *
     * @param actual the NewznabXmlItem we want to make assertions on.
     * @return a new <code>{@link NewznabXmlItemAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static NewznabXmlItemAssert assertThat(NewznabXmlItem actual) {
        return new NewznabXmlItemAssert(actual);
    }
}
