package org.nzbhydra.mapping.newznab.xml;

/**
 * {@link NewznabXmlGuid} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractNewznabXmlGuidAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class NewznabXmlGuidAssert extends AbstractNewznabXmlGuidAssert<NewznabXmlGuidAssert, NewznabXmlGuid> {

    /**
     * Creates a new <code>{@link NewznabXmlGuidAssert}</code> to make assertions on actual NewznabXmlGuid.
     *
     * @param actual the NewznabXmlGuid we want to make assertions on.
     */
    public NewznabXmlGuidAssert(NewznabXmlGuid actual) {
        super(actual, NewznabXmlGuidAssert.class);
    }

    /**
     * An entry point for NewznabXmlGuidAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myNewznabXmlGuid)</code> and get specific assertion with code completion.
     *
     * @param actual the NewznabXmlGuid we want to make assertions on.
     * @return a new <code>{@link NewznabXmlGuidAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static NewznabXmlGuidAssert assertThat(NewznabXmlGuid actual) {
        return new NewznabXmlGuidAssert(actual);
    }
}
