package org.nzbhydra.mapping.newznab.builder;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link RssChannelBuilder} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractRssChannelBuilderAssert<S extends AbstractRssChannelBuilderAssert<S, A>, A extends RssChannelBuilder> extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractRssChannelBuilderAssert}</code> to make assertions on actual RssChannelBuilder.
     *
     * @param actual the RssChannelBuilder we want to make assertions on.
     */
    protected AbstractRssChannelBuilderAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
