package org.nzbhydra.mapping.newznab.builder;

/**
 * {@link RssBuilder} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractRssBuilderAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class RssBuilderAssert extends AbstractRssBuilderAssert<RssBuilderAssert, RssBuilder> {

    /**
     * Creates a new <code>{@link RssBuilderAssert}</code> to make assertions on actual RssBuilder.
     *
     * @param actual the RssBuilder we want to make assertions on.
     */
    public RssBuilderAssert(RssBuilder actual) {
        super(actual, RssBuilderAssert.class);
    }

    /**
     * An entry point for RssBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myRssBuilder)</code> and get specific assertion with code completion.
     *
     * @param actual the RssBuilder we want to make assertions on.
     * @return a new <code>{@link RssBuilderAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static RssBuilderAssert assertThat(RssBuilder actual) {
        return new RssBuilderAssert(actual);
    }
}
