package org.nzbhydra.mapping.newznab.builder;

/**
 * {@link RssChannelBuilder} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractRssChannelBuilderAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class RssChannelBuilderAssert extends AbstractRssChannelBuilderAssert<RssChannelBuilderAssert, RssChannelBuilder> {

    /**
     * Creates a new <code>{@link RssChannelBuilderAssert}</code> to make assertions on actual RssChannelBuilder.
     *
     * @param actual the RssChannelBuilder we want to make assertions on.
     */
    public RssChannelBuilderAssert(RssChannelBuilder actual) {
        super(actual, RssChannelBuilderAssert.class);
    }

    /**
     * An entry point for RssChannelBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myRssChannelBuilder)</code> and get specific assertion with code completion.
     *
     * @param actual the RssChannelBuilder we want to make assertions on.
     * @return a new <code>{@link RssChannelBuilderAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static RssChannelBuilderAssert assertThat(RssChannelBuilder actual) {
        return new RssChannelBuilderAssert(actual);
    }
}
