package org.nzbhydra.mapping.newznab.builder;

/**
 * {@link RssItemBuilder} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractRssItemBuilderAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class RssItemBuilderAssert extends AbstractRssItemBuilderAssert<RssItemBuilderAssert, RssItemBuilder> {

    /**
     * Creates a new <code>{@link RssItemBuilderAssert}</code> to make assertions on actual RssItemBuilder.
     *
     * @param actual the RssItemBuilder we want to make assertions on.
     */
    public RssItemBuilderAssert(RssItemBuilder actual) {
        super(actual, RssItemBuilderAssert.class);
    }

    /**
     * An entry point for RssItemBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myRssItemBuilder)</code> and get specific assertion with code completion.
     *
     * @param actual the RssItemBuilder we want to make assertions on.
     * @return a new <code>{@link RssItemBuilderAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static RssItemBuilderAssert assertThat(RssItemBuilder actual) {
        return new RssItemBuilderAssert(actual);
    }
}
