package org.nzbhydra.historystats;

/**
 * {@link FilterDefinition} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractFilterDefinitionAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class FilterDefinitionAssert extends AbstractFilterDefinitionAssert<FilterDefinitionAssert, FilterDefinition> {

    /**
     * Creates a new <code>{@link FilterDefinitionAssert}</code> to make assertions on actual FilterDefinition.
     *
     * @param actual the FilterDefinition we want to make assertions on.
     */
    public FilterDefinitionAssert(FilterDefinition actual) {
        super(actual, FilterDefinitionAssert.class);
    }

    /**
     * An entry point for FilterDefinitionAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myFilterDefinition)</code> and get specific assertion with code completion.
     *
     * @param actual the FilterDefinition we want to make assertions on.
     * @return a new <code>{@link FilterDefinitionAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static FilterDefinitionAssert assertThat(FilterDefinition actual) {
        return new FilterDefinitionAssert(actual);
    }
}
