package org.nzbhydra.config.mediainfo;

import org.assertj.core.api.AbstractComparableAssert;

/**
 * Abstract base class for {@link MediaIdType} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractMediaIdTypeAssert<S extends AbstractMediaIdTypeAssert<S, A>, A extends MediaIdType> extends AbstractComparableAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractMediaIdTypeAssert}</code> to make assertions on actual MediaIdType.
     *
     * @param actual the MediaIdType we want to make assertions on.
     */
    protected AbstractMediaIdTypeAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
