package org.nzbhydra.downloading.downloaders.sabnzbd.mapping;

/**
 * {@link Queue} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractQueueAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class QueueAssert extends AbstractQueueAssert<QueueAssert, Queue> {

    /**
     * Creates a new <code>{@link QueueAssert}</code> to make assertions on actual Queue.
     *
     * @param actual the Queue we want to make assertions on.
     */
    public QueueAssert(Queue actual) {
        super(actual, QueueAssert.class);
    }

    /**
     * An entry point for QueueAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myQueue)</code> and get specific assertion with code completion.
     *
     * @param actual the Queue we want to make assertions on.
     * @return a new <code>{@link QueueAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static QueueAssert assertThat(Queue actual) {
        return new QueueAssert(actual);
    }
}
