package org.nzbhydra.historystats.stats;

/**
 * {@link DownloadPerAge} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractDownloadPerAgeAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class DownloadPerAgeAssert extends AbstractDownloadPerAgeAssert<DownloadPerAgeAssert, DownloadPerAge> {

    /**
     * Creates a new <code>{@link DownloadPerAgeAssert}</code> to make assertions on actual DownloadPerAge.
     *
     * @param actual the DownloadPerAge we want to make assertions on.
     */
    public DownloadPerAgeAssert(DownloadPerAge actual) {
        super(actual, DownloadPerAgeAssert.class);
    }

    /**
     * An entry point for DownloadPerAgeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myDownloadPerAge)</code> and get specific assertion with code completion.
     *
     * @param actual the DownloadPerAge we want to make assertions on.
     * @return a new <code>{@link DownloadPerAgeAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static DownloadPerAgeAssert assertThat(DownloadPerAge actual) {
        return new DownloadPerAgeAssert(actual);
    }
}
