package org.nzbhydra.historystats.stats;

/**
 * {@link HistoryRequest} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractHistoryRequestAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class HistoryRequestAssert extends AbstractHistoryRequestAssert<HistoryRequestAssert, HistoryRequest> {

    /**
     * Creates a new <code>{@link HistoryRequestAssert}</code> to make assertions on actual HistoryRequest.
     *
     * @param actual the HistoryRequest we want to make assertions on.
     */
    public HistoryRequestAssert(HistoryRequest actual) {
        super(actual, HistoryRequestAssert.class);
    }

    /**
     * An entry point for HistoryRequestAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myHistoryRequest)</code> and get specific assertion with code completion.
     *
     * @param actual the HistoryRequest we want to make assertions on.
     * @return a new <code>{@link HistoryRequestAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static HistoryRequestAssert assertThat(HistoryRequest actual) {
        return new HistoryRequestAssert(actual);
    }
}
