package org.nzbhydra.historystats.stats;

/**
 * {@link IndexerDownloadShare} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractIndexerDownloadShareAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class IndexerDownloadShareAssert extends AbstractIndexerDownloadShareAssert<IndexerDownloadShareAssert, IndexerDownloadShare> {

    /**
     * Creates a new <code>{@link IndexerDownloadShareAssert}</code> to make assertions on actual IndexerDownloadShare.
     *
     * @param actual the IndexerDownloadShare we want to make assertions on.
     */
    public IndexerDownloadShareAssert(IndexerDownloadShare actual) {
        super(actual, IndexerDownloadShareAssert.class);
    }

    /**
     * An entry point for IndexerDownloadShareAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myIndexerDownloadShare)</code> and get specific assertion with code completion.
     *
     * @param actual the IndexerDownloadShare we want to make assertions on.
     * @return a new <code>{@link IndexerDownloadShareAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static IndexerDownloadShareAssert assertThat(IndexerDownloadShare actual) {
        return new IndexerDownloadShareAssert(actual);
    }
}
