package org.nzbhydra.historystats.stats;

/**
 * {@link SuccessfulDownloadsPerIndexer} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractSuccessfulDownloadsPerIndexerAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class SuccessfulDownloadsPerIndexerAssert extends AbstractSuccessfulDownloadsPerIndexerAssert<SuccessfulDownloadsPerIndexerAssert, SuccessfulDownloadsPerIndexer> {

    /**
     * Creates a new <code>{@link SuccessfulDownloadsPerIndexerAssert}</code> to make assertions on actual SuccessfulDownloadsPerIndexer.
     *
     * @param actual the SuccessfulDownloadsPerIndexer we want to make assertions on.
     */
    public SuccessfulDownloadsPerIndexerAssert(SuccessfulDownloadsPerIndexer actual) {
        super(actual, SuccessfulDownloadsPerIndexerAssert.class);
    }

    /**
     * An entry point for SuccessfulDownloadsPerIndexerAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(mySuccessfulDownloadsPerIndexer)</code> and get specific assertion with code completion.
     *
     * @param actual the SuccessfulDownloadsPerIndexer we want to make assertions on.
     * @return a new <code>{@link SuccessfulDownloadsPerIndexerAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static SuccessfulDownloadsPerIndexerAssert assertThat(SuccessfulDownloadsPerIndexer actual) {
        return new SuccessfulDownloadsPerIndexerAssert(actual);
    }
}
