package org.nzbhydra.mapping.newznab.xml.caps.jackett;

/**
 * {@link JacketCapsXmlRoot} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractJacketCapsXmlRootAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class JacketCapsXmlRootAssert extends AbstractJacketCapsXmlRootAssert<JacketCapsXmlRootAssert, JacketCapsXmlRoot> {

    /**
     * Creates a new <code>{@link JacketCapsXmlRootAssert}</code> to make assertions on actual JacketCapsXmlRoot.
     *
     * @param actual the JacketCapsXmlRoot we want to make assertions on.
     */
    public JacketCapsXmlRootAssert(JacketCapsXmlRoot actual) {
        super(actual, JacketCapsXmlRootAssert.class);
    }

    /**
     * An entry point for JacketCapsXmlRootAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myJacketCapsXmlRoot)</code> and get specific assertion with code completion.
     *
     * @param actual the JacketCapsXmlRoot we want to make assertions on.
     * @return a new <code>{@link JacketCapsXmlRootAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static JacketCapsXmlRootAssert assertThat(JacketCapsXmlRoot actual) {
        return new JacketCapsXmlRootAssert(actual);
    }
}
