CREATE TABLE INDEXERSTATUS
(
  ID                   INTEGER PRIMARY KEY NOT NULL,
  DISABLED_PERMANENTLY BOOLEAN,
  DISABLED_UNTIL       TIMESTAMP,
  FIRST_FAILURE        TIMESTAMP,
  LAST_FAILURE         TIMESTAMP,
  LEVEL                INTEGER,
  REASON               VARCHAR(4000)
);

CREATE TABLE MOVIEINFO
(
  ID         INTEGER PRIMARY KEY NOT NULL,
  IMDB_ID    VARCHAR(255),
  POSTER_URL VARCHAR(255),
  TITLE      VARCHAR(255),
  TMDB_ID    VARCHAR(255),
  YEAR       INTEGER
);

CREATE TABLE SEARCH
(
  ID             INTEGER PRIMARY KEY NOT NULL,
  AUTHOR         VARCHAR(255),
  CATEGORY_NAME  VARCHAR(255),
  EPISODE        VARCHAR(255),
  QUERY          VARCHAR(255),
  SEARCH_TYPE    VARCHAR(255),
  SEASON         INTEGER,
  SOURCE         VARCHAR(255),
  TIME           TIMESTAMP,
  TITLE          VARCHAR(255),
  USER_AGENT     VARCHAR(255),
  USERNAME_OR_IP VARCHAR(255)
);

CREATE TABLE GENERIC_STORAGE_DATA
(
  ID   INTEGER PRIMARY KEY NOT NULL,
  DATA VARCHAR(255),
  KEY  VARCHAR(255)
);

CREATE TABLE IDENTIFIER_KEY_VALUE_PAIR
(
  ID               INTEGER PRIMARY KEY NOT NULL,
  IDENTIFIER_KEY   VARCHAR(255),
  IDENTIFIER_VALUE VARCHAR(255)
);

CREATE TABLE INDEXER
(
  ID        INTEGER PRIMARY KEY NOT NULL,
  NAME      VARCHAR(255),
  STATUS_ID INTEGER,
  CONSTRAINT FKI97W3VAGIEAICA0TQ0WXNHYB2 FOREIGN KEY (STATUS_ID) REFERENCES INDEXERSTATUS (ID)
);
CREATE UNIQUE INDEX UK_XIFS7FHUVN4UB7IGF11FQEP0_INDEX_9
  ON INDEXER (NAME);

CREATE TABLE INDEXERAPIACCESS
(
  ID            INTEGER PRIMARY KEY NOT NULL,
  ACCESS_TYPE   VARCHAR(255),
  ERROR         VARCHAR(4000),
  RESPONSE_TIME BIGINT,
  RESULT        VARCHAR(255),
  TIME          TIMESTAMP,
  INDEXER_ID    INTEGER,
  CONSTRAINT FKFLRMBYQ8CLDV48SWRYIY0YJD2 FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID)
);

CREATE TABLE INDEXERAPIACCESS_SHORT
(
  ID         INTEGER PRIMARY KEY NOT NULL,
  INDEXER_ID INTEGER,
  TIME       TIMESTAMP,
  SUCCESSFUL BOOLEAN,
  CONSTRAINT FKFLRMBYQ8CLDV48KDUNDZHD FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID)
);
CREATE INDEX INDEXERAPIACCESS_SHORT_INDEXER_ID_TIME_INDEX
  ON INDEXERAPIACCESS_SHORT (INDEXER_ID, TIME DESC);

CREATE TABLE INDEXERNZBDOWNLOAD
(
  ID              INTEGER PRIMARY KEY NOT NULL,
  ACCESS_SOURCE   VARCHAR(255),
  AGE             INTEGER,
  ERROR           VARCHAR(255),
  EXTERNAL_ID     VARCHAR(255),
  NZB_ACCESS_TYPE VARCHAR(255),
  STATUS          VARCHAR(255),
  TIME            TIMESTAMP,
  TITLE           VARCHAR(4000),
  USERNAME_OR_IP  VARCHAR(255),
  INDEXER_ID      INTEGER,
  CONSTRAINT FKMTRRF4HK98C9O3FDQJTS3HUPB FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID)
);
CREATE INDEX NZB_DOWNLOAD_EXT_ID
  ON INDEXERNZBDOWNLOAD (EXTERNAL_ID);
CREATE INDEX INDEXERNZBDOWNLOAD_INDEXER_ID_TIME_INDEX
  ON INDEXERNZBDOWNLOAD (INDEXER_ID, TIME DESC);

CREATE TABLE INDEXERSEARCH
(
  ID                INTEGER PRIMARY KEY NOT NULL,
  PROCESSED_RESULTS INTEGER,
  RESULTS_COUNT     INTEGER,
  SUCCESSFUL        BOOLEAN,
  UNIQUE_RESULTS    INTEGER,
  INDEXER_ENTITY_ID INTEGER,
  SEARCH_ENTITY_ID  INTEGER,
  CONSTRAINT FK48A7TLYKV21V8CEGF6SUCDYGX FOREIGN KEY (INDEXER_ENTITY_ID) REFERENCES INDEXER (ID),
  CONSTRAINT FKOBOGIXH7OUOCYK1M0417GYQKR FOREIGN KEY (SEARCH_ENTITY_ID) REFERENCES SEARCH (ID)
);
CREATE INDEX INDEXERSEARCH_INDEXER_ENTITY_ID_SEARCH_ENTITY_ID_INDEX
  ON INDEXERSEARCH (INDEXER_ENTITY_ID, SEARCH_ENTITY_ID);


CREATE TABLE PERSISTENT_LOGINS
(
  SERIES    VARCHAR(255) PRIMARY KEY NOT NULL,
  LAST_USED TIMESTAMP                NOT NULL,
  TOKEN     VARCHAR(255)             NOT NULL,
  USERNAME  VARCHAR(255)             NOT NULL
);

CREATE TABLE SEARCHRESULT
(
  ID            BIGINT PRIMARY KEY NOT NULL,
  DETAILS       VARCHAR(4000),
  DOWNLOAD_TYPE VARCHAR(255),
  FIRST_FOUND   TIMESTAMP,
  INDEXERGUID   VARCHAR(255)       NOT NULL,
  LINK          VARCHAR(4000),
  PUB_DATE      TIMESTAMP,
  TITLE         VARCHAR(4000)      NOT NULL,
  INDEXER_ID    INTEGER            NOT NULL,
  CONSTRAINT FKR5G21PDW3HHS1SEFVJY30TGMI FOREIGN KEY (INDEXER_ID) REFERENCES INDEXER (ID)
);
CREATE UNIQUE INDEX UKFTFA80663URIMM78EPNXHYOM_INDEX_C
  ON SEARCHRESULT (INDEXER_ID, INDEXERGUID);

CREATE TABLE SEARCH_IDENTIFIERS
(
  SEARCH_ENTITY_ID INTEGER NOT NULL,
  IDENTIFIERS_ID   INTEGER NOT NULL,
  CONSTRAINT CONSTRAINT_66 PRIMARY KEY (SEARCH_ENTITY_ID, IDENTIFIERS_ID),
  CONSTRAINT FKG7116YD6U2Q5LPQQLCLDKBVGL FOREIGN KEY (SEARCH_ENTITY_ID) REFERENCES SEARCH (ID),
  CONSTRAINT FK8V41HNWG7RV1GELG37QK9M7WK FOREIGN KEY (IDENTIFIERS_ID) REFERENCES IDENTIFIER_KEY_VALUE_PAIR (ID)
);

CREATE TABLE SHOWNNEWS
(
  ID      INTEGER PRIMARY KEY NOT NULL,
  VERSION VARCHAR(255)
);

CREATE TABLE TVINFO
(
  ID         INTEGER PRIMARY KEY NOT NULL,
  POSTER_URL VARCHAR(255),
  TITLE      VARCHAR(255),
  TVDB_ID    VARCHAR(255),
  TVMAZE_ID  VARCHAR(255),
  TVRAGE_ID  VARCHAR(255),
  YEAR       INTEGER
);
CREATE UNIQUE INDEX UK_PGYJIFSNJSVJ1W9P0XVIDGP5E_INDEX_9
  ON TVINFO (TVDB_ID);
CREATE UNIQUE INDEX UK_NJKRL57AGU954UJKOTT65HWHH_INDEX_9
  ON TVINFO (TVMAZE_ID);
CREATE UNIQUE INDEX UK_GFWLXF98S7J77CF7G6FSFVSS0_INDEX_9
  ON TVINFO (TVRAGE_ID);

CREATE SEQUENCE PUBLIC.hibernate_sequence;