package org.nzbhydra.mapping.newznab.mock;

/**
 * {@link NewznabMockBuilder} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractNewznabMockBuilderAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class NewznabMockBuilderAssert extends AbstractNewznabMockBuilderAssert<NewznabMockBuilderAssert, NewznabMockBuilder> {

    /**
     * Creates a new <code>{@link NewznabMockBuilderAssert}</code> to make assertions on actual NewznabMockBuilder.
     *
     * @param actual the NewznabMockBuilder we want to make assertions on.
     */
    public NewznabMockBuilderAssert(NewznabMockBuilder actual) {
        super(actual, NewznabMockBuilderAssert.class);
    }

    /**
     * An entry point for NewznabMockBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myNewznabMockBuilder)</code> and get specific assertion with code completion.
     *
     * @param actual the NewznabMockBuilder we want to make assertions on.
     * @return a new <code>{@link NewznabMockBuilderAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static NewznabMockBuilderAssert assertThat(NewznabMockBuilder actual) {
        return new NewznabMockBuilderAssert(actual);
    }
}
