package org.nzbhydra.config;

import org.assertj.core.api.AbstractComparableAssert;

/**
 * Abstract base class for {@link SearchSource} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractSearchSourceAssert<S extends AbstractSearchSourceAssert<S, A>, A extends SearchSource> extends AbstractComparableAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractSearchSourceAssert}</code> to make assertions on actual SearchSource.
     *
     * @param actual the SearchSource we want to make assertions on.
     */
    protected AbstractSearchSourceAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

}
