package org.nzbhydra.config;

/**
 * {@link BaseConfig} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractBaseConfigAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class BaseConfigAssert extends AbstractBaseConfigAssert<BaseConfigAssert, BaseConfig> {

    /**
     * Creates a new <code>{@link BaseConfigAssert}</code> to make assertions on actual BaseConfig.
     *
     * @param actual the BaseConfig we want to make assertions on.
     */
    public BaseConfigAssert(BaseConfig actual) {
        super(actual, BaseConfigAssert.class);
    }

    /**
     * An entry point for BaseConfigAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myBaseConfig)</code> and get specific assertion with code completion.
     *
     * @param actual the BaseConfig we want to make assertions on.
     * @return a new <code>{@link BaseConfigAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static BaseConfigAssert assertThat(BaseConfig actual) {
        return new BaseConfigAssert(actual);
    }
}
