package org.nzbhydra.config;

/**
 * {@link LoggingConfig} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractLoggingConfigAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class LoggingConfigAssert extends AbstractLoggingConfigAssert<LoggingConfigAssert, LoggingConfig> {

    /**
     * Creates a new <code>{@link LoggingConfigAssert}</code> to make assertions on actual LoggingConfig.
     *
     * @param actual the LoggingConfig we want to make assertions on.
     */
    public LoggingConfigAssert(LoggingConfig actual) {
        super(actual, LoggingConfigAssert.class);
    }

    /**
     * An entry point for LoggingConfigAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myLoggingConfig)</code> and get specific assertion with code completion.
     *
     * @param actual the LoggingConfig we want to make assertions on.
     * @return a new <code>{@link LoggingConfigAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static LoggingConfigAssert assertThat(LoggingConfig actual) {
        return new LoggingConfigAssert(actual);
    }
}
