package org.nzbhydra.mapping.newznab.json;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link NewznabJsonRootAttributes} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractNewznabJsonRootAttributesAssert<S extends AbstractNewznabJsonRootAttributesAssert<S, A>, A extends NewznabJsonRootAttributes> extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractNewznabJsonRootAttributesAssert}</code> to make assertions on actual NewznabJsonRootAttributes.
     *
     * @param actual the NewznabJsonRootAttributes we want to make assertions on.
     */
    protected AbstractNewznabJsonRootAttributesAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

    /**
     * Verifies that the actual NewznabJsonRootAttributes's version is equal to the given one.
     *
     * @param version the given version to compare the actual NewznabJsonRootAttributes's version to.
     * @return this assertion object.
     * @throws AssertionError - if the actual NewznabJsonRootAttributes's version is not equal to the given one.
     */
    public S hasVersion(String version) {
        // check that actual NewznabJsonRootAttributes we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting version of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // null safe check
        String actualVersion = actual.getVersion();
        if (!Objects.areEqual(actualVersion, version)) {
            failWithMessage(assertjErrorMessage, actual, version, actualVersion);
        }

        // return the current assertion for method chaining
        return myself;
    }

}
