package org.nzbhydra.mapping.newznab.json;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link NewznabJsonEnclosure} specific assertions - Generated by CustomAssertionGenerator.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public abstract class AbstractNewznabJsonEnclosureAssert<S extends AbstractNewznabJsonEnclosureAssert<S, A>, A extends NewznabJsonEnclosure> extends AbstractObjectAssert<S, A> {

    /**
     * Creates a new <code>{@link AbstractNewznabJsonEnclosureAssert}</code> to make assertions on actual NewznabJsonEnclosure.
     *
     * @param actual the NewznabJsonEnclosure we want to make assertions on.
     */
    protected AbstractNewznabJsonEnclosureAssert(A actual, Class<S> selfType) {
        super(actual, selfType);
    }

    /**
     * Verifies that the actual NewznabJsonEnclosure's attributes is equal to the given one.
     *
     * @param attributes the given attributes to compare the actual NewznabJsonEnclosure's attributes to.
     * @return this assertion object.
     * @throws AssertionError - if the actual NewznabJsonEnclosure's attributes is not equal to the given one.
     */
    public S hasAttributes(NewznabJsonEnclosureAttributes attributes) {
        // check that actual NewznabJsonEnclosure we want to make assertions on is not null.
        isNotNull();

        // overrides the default error message with a more explicit one
        String assertjErrorMessage = "\nExpecting attributes of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

        // null safe check
        NewznabJsonEnclosureAttributes actualAttributes = actual.getAttributes();
        if (!Objects.areEqual(actualAttributes, attributes)) {
            failWithMessage(assertjErrorMessage, actual, attributes, actualAttributes);
        }

        // return the current assertion for method chaining
        return myself;
    }

}
