package org.nzbhydra.mapping.newznab.json;

/**
 * {@link JsonPubdateDeserializer} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractJsonPubdateDeserializerAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class JsonPubdateDeserializerAssert extends AbstractJsonPubdateDeserializerAssert<JsonPubdateDeserializerAssert, JsonPubdateDeserializer> {

    /**
     * Creates a new <code>{@link JsonPubdateDeserializerAssert}</code> to make assertions on actual JsonPubdateDeserializer.
     *
     * @param actual the JsonPubdateDeserializer we want to make assertions on.
     */
    public JsonPubdateDeserializerAssert(JsonPubdateDeserializer actual) {
        super(actual, JsonPubdateDeserializerAssert.class);
    }

    /**
     * An entry point for JsonPubdateDeserializerAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myJsonPubdateDeserializer)</code> and get specific assertion with code completion.
     *
     * @param actual the JsonPubdateDeserializer we want to make assertions on.
     * @return a new <code>{@link JsonPubdateDeserializerAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static JsonPubdateDeserializerAssert assertThat(JsonPubdateDeserializer actual) {
        return new JsonPubdateDeserializerAssert(actual);
    }
}
