package org.nzbhydra.mapping.newznab.json;

/**
 * {@link JsonPubdateSerializer} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractJsonPubdateSerializerAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class JsonPubdateSerializerAssert extends AbstractJsonPubdateSerializerAssert<JsonPubdateSerializerAssert, JsonPubdateSerializer> {

    /**
     * Creates a new <code>{@link JsonPubdateSerializerAssert}</code> to make assertions on actual JsonPubdateSerializer.
     *
     * @param actual the JsonPubdateSerializer we want to make assertions on.
     */
    public JsonPubdateSerializerAssert(JsonPubdateSerializer actual) {
        super(actual, JsonPubdateSerializerAssert.class);
    }

    /**
     * An entry point for JsonPubdateSerializerAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myJsonPubdateSerializer)</code> and get specific assertion with code completion.
     *
     * @param actual the JsonPubdateSerializer we want to make assertions on.
     * @return a new <code>{@link JsonPubdateSerializerAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static JsonPubdateSerializerAssert assertThat(JsonPubdateSerializer actual) {
        return new JsonPubdateSerializerAssert(actual);
    }
}
