package org.nzbhydra.mapping.newznab.json;

/**
 * {@link NewznabJsonResponseAttributes} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractNewznabJsonResponseAttributesAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class NewznabJsonResponseAttributesAssert extends AbstractNewznabJsonResponseAttributesAssert<NewznabJsonResponseAttributesAssert, NewznabJsonResponseAttributes> {

    /**
     * Creates a new <code>{@link NewznabJsonResponseAttributesAssert}</code> to make assertions on actual NewznabJsonResponseAttributes.
     *
     * @param actual the NewznabJsonResponseAttributes we want to make assertions on.
     */
    public NewznabJsonResponseAttributesAssert(NewznabJsonResponseAttributes actual) {
        super(actual, NewznabJsonResponseAttributesAssert.class);
    }

    /**
     * An entry point for NewznabJsonResponseAttributesAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myNewznabJsonResponseAttributes)</code> and get specific assertion with code completion.
     *
     * @param actual the NewznabJsonResponseAttributes we want to make assertions on.
     * @return a new <code>{@link NewznabJsonResponseAttributesAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static NewznabJsonResponseAttributesAssert assertThat(NewznabJsonResponseAttributes actual) {
        return new NewznabJsonResponseAttributesAssert(actual);
    }
}
