package org.nzbhydra.mapping.newznab.json;

/**
 * {@link NewznabJsonEnclosureAttributes} specific assertions - Generated by CustomAssertionGenerator.
 * <p>
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractNewznabJsonEnclosureAttributesAssert} instead.
 */
@jakarta.annotation.Generated(value = "assertj-assertions-generator")
public class NewznabJsonEnclosureAttributesAssert extends AbstractNewznabJsonEnclosureAttributesAssert<NewznabJsonEnclosureAttributesAssert, NewznabJsonEnclosureAttributes> {

    /**
     * Creates a new <code>{@link NewznabJsonEnclosureAttributesAssert}</code> to make assertions on actual NewznabJsonEnclosureAttributes.
     *
     * @param actual the NewznabJsonEnclosureAttributes we want to make assertions on.
     */
    public NewznabJsonEnclosureAttributesAssert(NewznabJsonEnclosureAttributes actual) {
        super(actual, NewznabJsonEnclosureAttributesAssert.class);
    }

    /**
     * An entry point for NewznabJsonEnclosureAttributesAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one can write directly: <code>assertThat(myNewznabJsonEnclosureAttributes)</code> and get specific assertion with code completion.
     *
     * @param actual the NewznabJsonEnclosureAttributes we want to make assertions on.
     * @return a new <code>{@link NewznabJsonEnclosureAttributesAssert}</code>
     */
    @org.assertj.core.util.CheckReturnValue
    public static NewznabJsonEnclosureAttributesAssert assertThat(NewznabJsonEnclosureAttributes actual) {
        return new NewznabJsonEnclosureAttributesAssert(actual);
    }
}
